pimcore:
    objects:
        class_definitions:
            data:
                map:
                    serializedStorageStructuredTable: \Factotum\SerializedStorageStructuredTableBundle\Model\DataObject\ClassDefinition\Data\SerializedStorageStructuredTable
